[package]
name = "polygon_unionfind"
version = "0.1.0"
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
std = []
stable-vec = ["dep:stable-vec", "maplike/stable-vec"]

[dependencies]
i_overlay = "4.4"
maplike = "0.8"
num-traits = "0.2"
rstar = "0.12"
rstared = "0.8"
stable-vec = { version = "0.4", optional = true }

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
