[package]
name = "polygon_unionfind"
version = "0.3.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Disjoint-set data structure (union-find) for polygons."
repository = "https://codeberg.org/topola/polygon_unionfind"
documentation = "https://docs.rs/polygon_unionfind"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["geometry", "unionfind"]
categories = ["algorithms", "data-structures", "graphics", "mathematics"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
std = []

[dependencies]
i_overlay = "4.4"
maplike = "0.8"
num-traits = "0.2"
rstar = "0.12"
rstared = "0.8"
undoredo = { version = "0.8", features = ["derive", "rstar"], optional = true }

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
