# SPDX-FileCopyrightText: 2026 triangulator contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "macroquad_viewer"
version = "0.1.0"
edition = "2024"

[features]
undoredo = ["polygon_unionfind/undoredo"]

[dependencies]
i_overlay = "4.4"
macroquad = "0.4"
polygon_unionfind = { path = ".." }
rand = "0.8"
